name: Go Module Release

on:
  push:
    branches:
      - main  # Set your default branch here

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'  # Set the Go version to match your project requirements

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Automated Version Tagging
        id: semantic-version  # Add this line
        uses: paulhatch/semantic-version@v4.0.2
        with:
            branch: main
            tag_prefix: 'v'
            major_pattern: '(MAJOR)'
            minor_pattern: '(MINOR)'
            format: '${major}.${minor}.${patch}'
            bump_each_commit: false

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.semantic-version.outputs.version }}
          release_name: Release ${{ steps.semantic-version.outputs.version }}
          draft: false
          prerelease: false
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Push Tags
        run: |
            git remote set-url origin git@github.com:tkruer/go-redcap.git
            git push --follow-tags
        
